### ISSUE TITLE
Hi, is there any way to open an issue for your ABB B23 Branch of the SDM-Reader Code?

### ISSUE THREAD

**Issue by PyroRider** [steefan85/Nibe#1]
There dont seem to be a field for issues and I cant find any contact information from you but I got a problem with the code

**Comment by PyroRider** [comment]
Hi, thank you for answering
I am using your code to read the data from my ABB B23 and then I let the
esp send a http get request which transmits all the values to a php server
which then takes the data and writes it into a database. The problem is
that the first Value, the voltage of L1 is completly missing and all values
shift in the database so that U-L2 is in the field of U-L1, power of L1 is
in the field for current of L3 and so on, I pinned it down to the esp code
but cant figure out whats the problem. I tried reading the registers
direcly via the register adress but still got the wrong values.
Do you have any ideas how to fix this?
Thank you for your help
Yours, Erik

**Comment by PyroRider** [comment]
> Hi, sorry for my delay. This code was just a quick (and dirty) fork of the original code and I'm not developing on this at the moment.
> 
> Maybe I can help, but I'm not a software developer and just made these changes for myself.

Hi, jsut a short question, which ABB B23 energy meter do you have? I found out that by shifting all registers down by 2 I will get the wanted values

**Comment by steefan85** [comment]
Hi, it is an ABB B23 112-100.

Did you change the code yourself and now it works?

**Comment by PyroRider** [comment]
Hi, sorry for bothering you, I found out that I forgot to add the amoub of
Registers to read when calling the function. Leaving it away leads the code
to do this unexpected behaviour.
Case solved, its working now, thank you for your time

steefan85 ***@***.***> schrieb am So., 5. Feb. 2023, 09:34:

**Comment by steefan85** [comment]
Thanks for your information!
